export const BETA_LAUNCH_MODE = true;

export const BETA_MESSAGE =
  'GearUp Beta is live. Create your profile, list your gear, and explore tech listings. Rentals and transactions open soon.';

export const BETA_DISABLED_MESSAGE = 'Rentals and transactions open soon.';

export const BETA_BOOKING_MESSAGE =
  'Rental bookings are opening soon in GearUp Beta. You can explore listings and list your gear now.';

export const BETA_DEMO_MESSAGE =
  'Demo listing for beta preview. Real bookings open soon.';

export const BETA_LISTING_PHONE_MESSAGE =
  'Phone verification is coming soon. Add your phone number to list during beta.';

export const DEFAULT_LAUNCH_INTEREST = {
  wantsToRent: false,
  wantsToList: false,
  wantsToSell: false,
};

export const canListDuringBeta = (profile: any) =>
  !BETA_LAUNCH_MODE || Boolean(profile?.phone || profile?.phoneVerified);

export const DEMO_RENT_LISTINGS = [
  {
    id: 'demo-rent-hyd-4070-pc',
    isDemo: true,
    title: 'RTX 4070 Gaming PC',
    category: 'Desktops',
    tier: 'High',
    pricePerDay: 1400,
    status: 'AVAILABLE',
    city: 'Hyderabad',
    location: { city: 'Hyderabad', area: 'Madhapur', landmark: 'Demo pickup zone' },
    isGaming: true,
  },
  {
    id: 'demo-rent-hyd-ps5',
    isDemo: true,
    title: 'PlayStation 5',
    category: 'Consoles',
    tier: 'Mid',
    pricePerDay: 600,
    status: 'AVAILABLE',
    city: 'Hyderabad',
    location: { city: 'Hyderabad', area: 'Jubilee Hills', landmark: 'Demo pickup zone' },
  },
  {
    id: 'demo-rent-hyd-xbox-series-x',
    isDemo: true,
    title: 'Xbox Series X',
    category: 'Consoles',
    tier: 'Mid',
    pricePerDay: 550,
    status: 'AVAILABLE',
    city: 'Hyderabad',
    location: { city: 'Hyderabad', area: 'Gachibowli', landmark: 'Demo pickup zone' },
  },
  {
    id: 'demo-rent-hyd-canon-r50',
    isDemo: true,
    title: 'Canon EOS R50',
    category: 'Cameras',
    tier: 'Mid',
    pricePerDay: 800,
    status: 'AVAILABLE',
    city: 'Hyderabad',
    location: { city: 'Hyderabad', area: 'Banjara Hills', landmark: 'Demo pickup zone' },
  },
  {
    id: 'demo-rent-hyd-4060-laptop',
    isDemo: true,
    title: 'RTX 4060 Laptop',
    category: 'Laptops',
    tier: 'Mid',
    pricePerDay: 900,
    status: 'AVAILABLE',
    city: 'Hyderabad',
    location: { city: 'Hyderabad', area: 'Kondapur', landmark: 'Demo pickup zone' },
    isGaming: true,
  },
  {
    id: 'demo-rent-blr-macbook-air-m2',
    isDemo: true,
    title: 'MacBook Air M2',
    category: 'Laptops',
    tier: 'Mid',
    pricePerDay: 900,
    status: 'AVAILABLE',
    city: 'Bangalore',
    location: { city: 'Bangalore', area: 'Indiranagar', landmark: 'Demo pickup zone' },
  },
  {
    id: 'demo-rent-blr-4080-pc',
    isDemo: true,
    title: 'RTX 4080 Gaming PC',
    category: 'Desktops',
    tier: 'High',
    pricePerDay: 1800,
    status: 'AVAILABLE',
    city: 'Bangalore',
    location: { city: 'Bangalore', area: 'Koramangala', landmark: 'Demo pickup zone' },
    isGaming: true,
  },
  {
    id: 'demo-rent-blr-a6400',
    isDemo: true,
    title: 'Sony A6400 Camera',
    category: 'Cameras',
    tier: 'Mid',
    pricePerDay: 750,
    status: 'AVAILABLE',
    city: 'Bangalore',
    location: { city: 'Bangalore', area: 'HSR Layout', landmark: 'Demo pickup zone' },
  },
  {
    id: 'demo-rent-blr-240hz-monitor',
    isDemo: true,
    title: 'Gaming Monitor 240Hz',
    category: 'Monitors',
    tier: 'Mid',
    pricePerDay: 650,
    status: 'AVAILABLE',
    city: 'Bangalore',
    location: { city: 'Bangalore', area: 'Whitefield', landmark: 'Demo pickup zone' },
  },
  {
    id: 'demo-rent-mum-ps5-slim',
    isDemo: true,
    title: 'PS5 Slim',
    category: 'Consoles',
    tier: 'Mid',
    pricePerDay: 600,
    status: 'AVAILABLE',
    city: 'Mumbai',
    location: { city: 'Mumbai', area: 'Andheri West', landmark: 'Demo pickup zone' },
  },
  {
    id: 'demo-rent-mum-3070-pc',
    isDemo: true,
    title: 'RTX 3070 PC',
    category: 'Desktops',
    tier: 'Mid',
    pricePerDay: 1100,
    status: 'AVAILABLE',
    city: 'Mumbai',
    location: { city: 'Mumbai', area: 'Bandra', landmark: 'Demo pickup zone' },
    isGaming: true,
  },
  {
    id: 'demo-rent-mum-gopro',
    isDemo: true,
    title: 'GoPro Hero',
    category: 'Cameras',
    tier: 'Low',
    pricePerDay: 450,
    status: 'AVAILABLE',
    city: 'Mumbai',
    location: { city: 'Mumbai', area: 'Powai', landmark: 'Demo pickup zone' },
  },
  {
    id: 'demo-rent-mum-macbook-pro-m1',
    isDemo: true,
    title: 'MacBook Pro M1',
    category: 'Laptops',
    tier: 'Mid',
    pricePerDay: 1000,
    status: 'AVAILABLE',
    city: 'Mumbai',
    location: { city: 'Mumbai', area: 'Lower Parel', landmark: 'Demo pickup zone' },
  },
];

export const DEMO_SALE_LISTINGS = [
  {
    id: 'demo-sale-hyd-4070-pc',
    isDemo: true,
    sellerId: 'demo-seller',
    sellerName: 'GearUp Demo Seller',
    title: 'RTX 4070 Gaming PC',
    category: 'Gaming PCs',
    condition: 'Excellent',
    price: 92000,
    description: 'Demo sale listing for beta preview.',
    status: 'ACTIVE',
    city: 'Hyderabad',
    photos: [],
    addressSnapshot: { city: 'Hyderabad', area: 'Madhapur', formattedAddress: 'Madhapur, Hyderabad' },
  },
  {
    id: 'demo-sale-hyd-ps5',
    isDemo: true,
    sellerId: 'demo-seller',
    sellerName: 'GearUp Demo Seller',
    title: 'PlayStation 5',
    category: 'Consoles',
    condition: 'Like New',
    price: 39000,
    description: 'Demo sale listing for beta preview.',
    status: 'ACTIVE',
    city: 'Hyderabad',
    photos: [],
    addressSnapshot: { city: 'Hyderabad', area: 'Jubilee Hills', formattedAddress: 'Jubilee Hills, Hyderabad' },
  },
  {
    id: 'demo-sale-hyd-canon-r50',
    isDemo: true,
    sellerId: 'demo-seller',
    sellerName: 'GearUp Demo Seller',
    title: 'Canon EOS R50',
    category: 'Cameras',
    condition: 'Good',
    price: 52000,
    description: 'Demo sale listing for beta preview.',
    status: 'ACTIVE',
    city: 'Hyderabad',
    photos: [],
    addressSnapshot: { city: 'Hyderabad', area: 'Banjara Hills', formattedAddress: 'Banjara Hills, Hyderabad' },
  },
  {
    id: 'demo-sale-hyd-xbox-series-x',
    isDemo: true,
    sellerId: 'demo-seller',
    sellerName: 'GearUp Demo Seller',
    title: 'Xbox Series X',
    category: 'Consoles',
    condition: 'Excellent',
    price: 35000,
    description: 'Demo sale listing for beta preview.',
    status: 'ACTIVE',
    city: 'Hyderabad',
    photos: [],
    addressSnapshot: { city: 'Hyderabad', area: 'Gachibowli', formattedAddress: 'Gachibowli, Hyderabad' },
  },
  {
    id: 'demo-sale-hyd-4060-laptop',
    isDemo: true,
    sellerId: 'demo-seller',
    sellerName: 'GearUp Demo Seller',
    title: 'RTX 4060 Laptop',
    category: 'Laptops',
    condition: 'Good',
    price: 78000,
    description: 'Demo sale listing for beta preview.',
    status: 'ACTIVE',
    city: 'Hyderabad',
    photos: [],
    addressSnapshot: { city: 'Hyderabad', area: 'Kondapur', formattedAddress: 'Kondapur, Hyderabad' },
  },
  {
    id: 'demo-sale-blr-macbook-air-m2',
    isDemo: true,
    sellerId: 'demo-seller',
    sellerName: 'GearUp Demo Seller',
    title: 'MacBook Air M2',
    category: 'Laptops',
    condition: 'Excellent',
    price: 68000,
    description: 'Demo sale listing for beta preview.',
    status: 'ACTIVE',
    city: 'Bangalore',
    photos: [],
    addressSnapshot: { city: 'Bangalore', area: 'Indiranagar', formattedAddress: 'Indiranagar, Bangalore' },
  },
  {
    id: 'demo-sale-blr-4080-pc',
    isDemo: true,
    sellerId: 'demo-seller',
    sellerName: 'GearUp Demo Seller',
    title: 'RTX 4080 Gaming PC',
    category: 'Gaming PCs',
    condition: 'Like New',
    price: 145000,
    description: 'Demo sale listing for beta preview.',
    status: 'ACTIVE',
    city: 'Bangalore',
    photos: [],
    addressSnapshot: { city: 'Bangalore', area: 'Koramangala', formattedAddress: 'Koramangala, Bangalore' },
  },
  {
    id: 'demo-sale-blr-a6400',
    isDemo: true,
    sellerId: 'demo-seller',
    sellerName: 'GearUp Demo Seller',
    title: 'Sony A6400 Camera',
    category: 'Cameras',
    condition: 'Good',
    price: 48000,
    description: 'Demo sale listing for beta preview.',
    status: 'ACTIVE',
    city: 'Bangalore',
    photos: [],
    addressSnapshot: { city: 'Bangalore', area: 'HSR Layout', formattedAddress: 'HSR Layout, Bangalore' },
  },
  {
    id: 'demo-sale-blr-240hz-monitor',
    isDemo: true,
    sellerId: 'demo-seller',
    sellerName: 'GearUp Demo Seller',
    title: 'Gaming Monitor 240Hz',
    category: 'Monitors',
    condition: 'Excellent',
    price: 22000,
    description: 'Demo sale listing for beta preview.',
    status: 'ACTIVE',
    city: 'Bangalore',
    photos: [],
    addressSnapshot: { city: 'Bangalore', area: 'Whitefield', formattedAddress: 'Whitefield, Bangalore' },
  },
  {
    id: 'demo-sale-mum-ps5-slim',
    isDemo: true,
    sellerId: 'demo-seller',
    sellerName: 'GearUp Demo Seller',
    title: 'PS5 Slim',
    category: 'Consoles',
    condition: 'Excellent',
    price: 36000,
    description: 'Demo sale listing for beta preview.',
    status: 'ACTIVE',
    city: 'Mumbai',
    photos: [],
    addressSnapshot: { city: 'Mumbai', area: 'Andheri West', formattedAddress: 'Andheri West, Mumbai' },
  },
  {
    id: 'demo-sale-mum-macbook-pro-m1',
    isDemo: true,
    sellerId: 'demo-seller',
    sellerName: 'GearUp Demo Seller',
    title: 'MacBook Pro M1',
    category: 'Laptops',
    condition: 'Good',
    price: 72000,
    description: 'Demo sale listing for beta preview.',
    status: 'ACTIVE',
    city: 'Mumbai',
    photos: [],
    addressSnapshot: { city: 'Mumbai', area: 'Lower Parel', formattedAddress: 'Lower Parel, Mumbai' },
  },
  {
    id: 'demo-sale-mum-3070-pc',
    isDemo: true,
    sellerId: 'demo-seller',
    sellerName: 'GearUp Demo Seller',
    title: 'RTX 3070 PC',
    category: 'Gaming PCs',
    condition: 'Good',
    price: 76000,
    description: 'Demo sale listing for beta preview.',
    status: 'ACTIVE',
    city: 'Mumbai',
    photos: [],
    addressSnapshot: { city: 'Mumbai', area: 'Bandra', formattedAddress: 'Bandra, Mumbai' },
  },
  {
    id: 'demo-sale-mum-gopro',
    isDemo: true,
    sellerId: 'demo-seller',
    sellerName: 'GearUp Demo Seller',
    title: 'GoPro Hero',
    category: 'Cameras',
    condition: 'Good',
    price: 21000,
    description: 'Demo sale listing for beta preview.',
    status: 'ACTIVE',
    city: 'Mumbai',
    photos: [],
    addressSnapshot: { city: 'Mumbai', area: 'Powai', formattedAddress: 'Powai, Mumbai' },
  },
];
